version: "3.8"
services:
  db:
    container_name: barcamp-db
    image: mysql:5.7.26
    ports:
      - "33006:3306"
    volumes:
      - type: volume
        source: data
        target: /var/lib/mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=barcamp
    networks:
      - barcamp-network
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  webapp:
    image: eduarobaldera/barcamp:final
    ports:
      - "80:8080"
    volumes:
      - ./build/libs:/home/app
    depends_on:
      - db
    networks:
      - barcamp-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://barcamp-db:3306/barcamp?autoReconnect=true&useSSL=false
volumes:
  data:

networks:
  barcamp-network: